server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: C:\Temp\positions.yaml

clients:
  - url: http://seu.loki.com.br:10060/loki/api/v1/push

scrape_configs:
  - job_name: windows-security-create-group
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=4727)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-create-group
        agent: promtail

  - job_name: windows-security-delete-group
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=4730)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-delete-group
        agent: promtail

  - job_name: windows-security-delete-user-from-group
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=4729)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-delete-user-from-group
        agent: promtail

  - job_name: windows-security-add-user-to-group
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=4728)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-add-user-to-group
        agent: promtail

  - job_name: windows-security-disable-user-account
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=4725)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-disable-user-account
        agent: promtail

  - job_name: windows-security-enable-user-account
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=4722)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-enable-user-account
        agent: promtail

  - job_name: windows-security-move-users-between-OUs
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=5139)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-move-users-between-OUs
        agent: promtail

  - job_name: windows-security-object-modified
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=4738)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-object-modified
        agent: promtail

  - job_name: windows-security-ou-created
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=5137)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-ou-created
        agent: promtail

  - job_name: windows-security-ou-deleted
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=5141)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-ou-deleted
        agent: promtail

  - job_name: windows-security-create-user
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=4720)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-create-user
        agent: promtail

  - job_name: windows-security-delete-user
    windows_events:
      locale: 1033
      use_incoming_timestamp: true
      exclude_event_data: false
      exclude_user_data: false
      bookmark_path: C:\Temp\bookmark-sys.xml
      eventlog_name: "Security"
      xpath_query: 'Event/System[(EventID=4726)]'
      labels:
        logsource: windows-eventlog
        job: windows-security-delete-user
        agent: promtail